[shell]
program = "/bin/zsh"
args = ["-l"]


[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 0, lines = 0 }
position = { x = 0, y = 0 }
padding = { x = 15, y = 15 }
dynamic_padding = true
decorations = "none"
startup_mode = "Windowed"
title = "Terminal"
dynamic_title = false

[scrolling]
history = 500
multiplier = 3

[font]
normal = { family = "SF Mono", style = "Retina" }
bold = { family = "SF Mono", style = "Semibold" }
italic = { family = "SF Mono", style = "Italic" }
bold_italic = { family = "SF Mono", style = "Semibold Italic" }
size = 10.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors.primary]
background = "0x002B36"
foreground = "0x839496"

[colors.normal]
black = "0x073642"
red = "0xdc322f"
green = "0x859900"
yellow = "0xb58900"
blue = "0x268bd2"
magenta = "0xd33682"
cyan = "0x2aa198"
white = "0xeee8d5"

[colors.bright]
black = "0x002b36"
red = "0xcb4b16"
green = "0x586e75"
yellow = "0x657b83"
blue = "0x839496"
magenta = "0x6c71c4"
cyan = "0x93a1a1"
white = "0xfdf6e3"

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = "None"
blink_interval = 750
unfocused_hollow = true
thickness = 0.15

[mouse]
    hide_when_typing = false
    bindings = [
        { mouse = "Right", mods = "Command", action = "Paste" },
    ]

[keyboard]
    bindings = [
        { key = "C", mods = "Command", action = "Copy" },
        { key = "V", mods = "Command", action = "Paste" },
        { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
        { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
    ]
